[package]
name = "xesite"
version = "0.1.0"
authors = ["Christine Dodrill <me@christine.website>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
comrak = "0.7"
handlebars = "3.2.1"
log = "0"
pretty_env_logger = "0"
rand = "0"
serde_dhall = "0.5.3"
serde = { version = "1", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
