name: "Nix"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v6
      - uses: cachix/cachix-action@v3
        with:
          name: xe
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          docker load -i result
          docker tag xena/christinewebsite:latest xena/christinewebsite:$GITHUB_SHA
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push xena/christinewebsite
        env:
          DOCKER_USERNAME: "xena"
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  release:
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: cachix/install-nix-action@v6
      - name: deploy
        run: ./scripts/release.sh
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          MI_TOKEN: ${{ secrets.MI_TOKEN }}
          PATREON_ACCESS_TOKEN: ${{ secrets.PATREON_ACCESS_TOKEN }}
          PATREON_CLIENT_ID: ${{ secrets.PATREON_CLIENT_ID }}
          PATREON_CLIENT_SECRET: ${{ secrets.PATREON_CLIENT_SECRET }}
          PATREON_REFRESH_TOKEN: ${{ secrets.PATREON_REFRESH_TOKEN }}
