name: Rust
on:
  push: master
  pull_request: master
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all
    - name: Run tests
      run: cargo test --all
